# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-dkiGO3Xs4n4OsQNMGOLHuP4r8WDtjzS
"""

import tensorflow as tf
from tensorflow import keras
import typing_extensions


loaded_model = tf.keras.models.load_model('eff_model.h5')

import streamlit as st
st.title(" Cat and Dog Classification")
st.header("This is a simple image classification web app to classify image of dog and cat")
file = st.file_uploader("Please upload an image file (JPG file only)", type=["jpg"])

from PIL import Image
import numpy as np

def import_and_predict(input_image, model):
        input_image = input_image.resize((224,224))
        input_image = np.asarray(input_image)
        input_image = np.expand_dims(input_image, axis = 0)         
        prediction = model.predict(input_image)

        animal_dict = {0:'Cat', 1:'Dog'}
        result = animal_dict[round(prediction[0][0])]
        
        if result == 'Dog':
          st.header("It is a dog!")
        else:
          st.header("It is a cat!")

if file is None:
    st.text("Please upload an image file (JPG file only)")
else:
    image = Image.open(file)
    st.image(image, use_column_width=True)
    prediction = import_and_predict(image, loaded_model)

